title: Anushka Rao
logo: /assets/Images/headshot.png
description: >
  Data Science Student at UC Davis  
  Email: [arrrao@ucdavis.edu](mailto:arrrao@ucdavis.edu)  
  LinkedIn: [anushkarao5](https://www.linkedin.com/in/anushkarao5/)
# show_downloads: true
theme: jekyll-theme-minimal
