title: "Anushka Rao"
# logo: "/assets/Images/headshot.png"
description: |
  Data Science Student at UC Davis  

# Uncomment the following line if you want to show download links
# show_downloads: true

theme: jekyll-theme-minimal
